name: Détection du type d'évènement

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PUSH_MESSAGE: "C'est un push !"
  PR_MESSAGE: "C'est une pull request !"

jobs:
  push_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "$PUSH_MESSAGE"

  pull_request_job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo "$PR_MESSAGE"
      
- run: echo "Event = ${{ github.event_name }}"
